import { createContext, useContext, useState, ReactNode } from "react";

export type Language = 'en' | 'ta' | 'hi' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "Farm AI",
    subtitle: "Your Smart Farming Companion",
    getStarted: "Get Started",
    howItWorks: "How It Works",
    howItWorksSubtitle: "Follow these 4 simple steps for smart farming",
    checkWeather: "Check Weather",
    checkWeatherDesc: "Get real-time weather & harvest recommendations for your location.",
    analyzeCrop: "Analyze Your Crop",
    analyzeCropDesc: "Capture or upload a photo for disease detection, or ask voice questions.",
    mlPrediction: "ML Fertilizer Prediction",
    mlPredictionDesc: "Enter crop & soil details to get precise NPK recommendations.",
    fertilizerGuide: "Fertilizer Guide",
    fertilizerGuideDesc: "Browse detailed guides for your specific crop and soil type.",
    beginStep1: "Begin Step 1",
    weatherTitle: "Weather & Harvest Recommendation",
    weatherSubtitle: "Real-time weather analysis for your farm location",
    nextCropAnalysis: "Next: Crop Analysis",
    cropAnalysisTitle: "Crop Analysis & Voice Help",
    cropAnalysisSubtitle: "Upload a crop photo or ask questions in your language",
    analyzeAndAsk: "Analyze Crop & Ask Questions",
    nextMLPredictor: "Next: ML Fertilizer Predictor",
    mlPowered: "ML-Powered Prediction",
    nextFertilizerGuide: "Next: Fertilizer Guide",
    detailedFertilizerGuide: "Detailed Fertilizer Guide",
    detailedFertilizerGuideSubtitle: "Comprehensive crop-specific fertilizer recommendations",
    empowering: "Empowering farmers with smart technology",
    copyright: "© 2024 Farm AI. Made with ❤️ for Farmers",
    // Weather
    weather: "Weather",
    cropAnalysis: "Crop Analysis",
    mlPredictor: "ML Predictor",
    guide: "Guide",
    // CropCapture
    cropImageAnalysis: "Crop Image Analysis",
    tapToCapture: "Tap to Capture Crop Image",
    orUpload: "or upload from gallery",
    camera: "Camera",
    upload: "Upload",
    analyzingCrop: "Analyzing your crop...",
    analysisComplete: "Analysis Complete",
    captureNew: "Capture New Image",
    cropHealthy: "🌾 Crop appears healthy! Good moisture levels detected. Recommended action: Continue regular watering schedule. Estimated time to harvest: 2-3 weeks.",
    // Voice
    voiceAssistant: "Voice Assistant",
    selectLanguage: "Select Your Language",
    processing: "Processing...",
    listeningSpeak: "Listening... Speak now",
    tapToAsk: "Tap to ask a question",
    askAbout: "Ask about harvesting, irrigation, pests, fertilizers, or weather",
    youSaid: "You said:",
    assistantResponse: "Assistant Response:",
    listen: "Listen",
    speechNotSupported: "Speech recognition is not supported in your browser. Please use Chrome or Edge.",
    failedMic: "Failed to start microphone. Please check permissions.",
    // ML Predictor
    fertilizerPredictor: "Fertilizer Predictor",
    serverSideAlgo: "Server-side Decision Tree + Weighted Scoring Algorithm",
    inputParameters: "Input Parameters",
    cropType: "Crop Type",
    selectCrop: "Select crop",
    soilType: "Soil Type",
    growthStage: "Growth Stage",
    weatherCondition: "Weather Condition",
    temperature: "Temperature (°C)",
    farmArea: "Farm Area (Acres)",
    runningML: "Running ML Algorithm...",
    predictFertilizer: "Predict Fertilizer Requirements",
    predictionConfidence: "Prediction Confidence",
    basedOnDecision: "Based on Decision Tree classification with weighted scoring",
    kgNitrogen: "kg Nitrogen (N)",
    forLeafGrowth: "For leaf growth & chlorophyll",
    kgPhosphorus: "kg Phosphorus (P)",
    forRootDev: "For root development",
    kgPotassium: "kg Potassium (K)",
    forFruitDisease: "For fruit & disease resistance",
    recommendedProducts: "Recommended Fertilizer Products",
    applicationMethod: "Application Method",
    bestTiming: "Best Timing",
    warnings: "Warnings",
    mlAlgoDetails: "🧠 ML Algorithm Details",
    selectCropError: "Please select a crop",
    predictionComplete: "ML prediction complete from backend!",
    predictionFailed: "Failed to get prediction. Please try again.",
    // Location
    selectLocation: "Select location",
    currentLocation: "Current Location",
    fetchingWeather: "Fetching weather data...",
    unableToFetch: "Unable to fetch weather data",
    tryAgain: "Please try again later",
    humidity: "Humidity",
    wind: "Wind",
    feelsLike: "Feels Like",
    goodForHarvest: "✓ Good for Harvest",
    waitToHarvest: "⏳ Wait to Harvest",
    // Crop Suggestions
    cropSuggestions: "Crop Suggestions",
    cropSuggestionsDesc: "AI suggests the best crops based on current weather conditions.",
    cropSuggestionsTitle: "Best Crops for Today's Weather",
    cropSuggestionsSubtitle: "Select a crop to get fertilizer recommendations",
    nextCropSuggestions: "Next: Crop Suggestions",
    checkWeatherFirst: "Check weather first",
    checkWeatherFirstDesc: "Weather data is needed to suggest suitable crops",
    analyzingWeatherForCrops: "Analyzing weather for best crops...",
    suitability: "Suitability",
    season: "Season",
    harvestIn: "Harvest in",
    selectedCrop: "Selected Crop",
    nextGetFertilizer: "Get fertilizer recommendations",
    aiEnhancedTip: "AI Farming Tip",
    farmingTip: "Farming Tip",
    additionalTools: "Additional Tools",
  },
  ta: {
    appName: "Farm AI",
    subtitle: "உங்கள் ஸ்மார்ட் விவசாய தோழன்",
    getStarted: "தொடங்குங்கள்",
    howItWorks: "இது எப்படி செயல்படுகிறது",
    howItWorksSubtitle: "ஸ்மார்ட் விவசாயத்திற்கு இந்த 4 எளிய படிகளைப் பின்பற்றுங்கள்",
    checkWeather: "வானிலை பாருங்கள்",
    checkWeatherDesc: "உங்கள் இருப்பிடத்திற்கான நிகழ்நேர வானிலை மற்றும் அறுவடை பரிந்துரைகளைப் பெறுங்கள்.",
    analyzeCrop: "பயிரை ஆராயுங்கள்",
    analyzeCropDesc: "நோய் கண்டறிதலுக்கு புகைப்படம் எடுக்கவும் அல்லது குரல் கேள்விகள் கேளுங்கள்.",
    mlPrediction: "ML உர கணிப்பு",
    mlPredictionDesc: "துல்லியமான NPK பரிந்துரைகளுக்கு பயிர் மற்றும் மண் விவரங்களை உள்ளிடுங்கள்.",
    fertilizerGuide: "உர வழிகாட்டி",
    fertilizerGuideDesc: "உங்கள் குறிப்பிட்ட பயிர் மற்றும் மண் வகைக்கான விரிவான வழிகாட்டிகளை பாருங்கள்.",
    beginStep1: "படி 1 தொடங்குங்கள்",
    weatherTitle: "வானிலை & அறுவடை பரிந்துரை",
    weatherSubtitle: "உங்கள் பண்ணை இருப்பிடத்திற்கான நிகழ்நேர வானிலை பகுப்பாய்வு",
    nextCropAnalysis: "அடுத்தது: பயிர் பகுப்பாய்வு",
    cropAnalysisTitle: "பயிர் பகுப்பாய்வு & குரல் உதவி",
    cropAnalysisSubtitle: "பயிர் புகைப்படத்தை பதிவேற்றவும் அல்லது உங்கள் மொழியில் கேள்விகள் கேளுங்கள்",
    analyzeAndAsk: "பயிரை ஆராய்ந்து கேள்விகள் கேளுங்கள்",
    nextMLPredictor: "அடுத்தது: ML உர கணிப்பான்",
    mlPowered: "ML-இயக்கப்படும் கணிப்பு",
    nextFertilizerGuide: "அடுத்தது: உர வழிகாட்டி",
    detailedFertilizerGuide: "விரிவான உர வழிகாட்டி",
    detailedFertilizerGuideSubtitle: "விரிவான பயிர்-குறிப்பிட்ட உர பரிந்துரைகள்",
    empowering: "ஸ்மார்ட் தொழில்நுட்பத்துடன் விவசாயிகளை வலுப்படுத்துதல்",
    copyright: "© 2024 Farm AI. விவசாயிகளுக்காக ❤️ உடன் உருவாக்கப்பட்டது",
    weather: "வானிலை",
    cropAnalysis: "பயிர் பகுப்பாய்வு",
    mlPredictor: "ML கணிப்பான்",
    guide: "வழிகாட்டி",
    cropImageAnalysis: "பயிர் புகைப்பட பகுப்பாய்வு",
    tapToCapture: "பயிர் படத்தை எடுக்க தட்டவும்",
    orUpload: "அல்லது கேலரியிலிருந்து பதிவேற்றவும்",
    camera: "கேமரா",
    upload: "பதிவேற்றம்",
    analyzingCrop: "உங்கள் பயிரை பகுப்பாய்வு செய்கிறது...",
    analysisComplete: "பகுப்பாய்வு முடிந்தது",
    captureNew: "புதிய படம் எடுக்கவும்",
    cropHealthy: "🌾 பயிர் ஆரோக்கியமாக தெரிகிறது! நல்ல ஈரப்பத அளவுகள் கண்டறியப்பட்டன. பரிந்துரைக்கப்படும் நடவடிக்கை: வழக்கமான நீர்ப்பாசன அட்டவணையை தொடருங்கள். அறுவடைக்கான மதிப்பீட்டு நேரம்: 2-3 வாரங்கள்.",
    voiceAssistant: "குரல் உதவியாளர்",
    selectLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    processing: "செயலாக்குகிறது...",
    listeningSpeak: "கேட்கிறேன்... இப்போது பேசுங்கள்",
    tapToAsk: "கேள்வி கேட்க தட்டவும்",
    askAbout: "அறுவடை, பாசனம், பூச்சிகள், உரங்கள் அல்லது வானிலை பற்றி கேளுங்கள்",
    youSaid: "நீங்கள் சொன்னது:",
    assistantResponse: "உதவியாளர் பதில்:",
    listen: "கேளுங்கள்",
    speechNotSupported: "உங்கள் உலாவியில் பேச்சு அங்கீகாரம் ஆதரிக்கப்படவில்லை. Chrome அல்லது Edge பயன்படுத்தவும்.",
    failedMic: "மைக்ரோஃபோனைத் தொடங்க முடியவில்லை. அனுமதிகளை சரிபாருங்கள்.",
    fertilizerPredictor: "உர கணிப்பான்",
    serverSideAlgo: "சர்வர்-சைட் முடிவு மரம் + எடையிடப்பட்ட மதிப்பெண் அல்காரிதம்",
    inputParameters: "உள்ளீட்டு அளவுருக்கள்",
    cropType: "பயிர் வகை",
    selectCrop: "பயிரைத் தேர்ந்தெடுக்கவும்",
    soilType: "மண் வகை",
    growthStage: "வளர்ச்சி நிலை",
    weatherCondition: "வானிலை நிலை",
    temperature: "வெப்பநிலை (°C)",
    farmArea: "பண்ணை பரப்பளவு (ஏக்கர்)",
    runningML: "ML அல்காரிதம் இயங்குகிறது...",
    predictFertilizer: "உர தேவைகளை கணிக்கவும்",
    predictionConfidence: "கணிப்பு நம்பிக்கை",
    basedOnDecision: "எடையிடப்பட்ட மதிப்பெண் உடன் முடிவு மரம் வகைப்படுத்தல் அடிப்படையில்",
    kgNitrogen: "கிலோ நைட்ரஜன் (N)",
    forLeafGrowth: "இலை வளர்ச்சி & குளோரோபில்",
    kgPhosphorus: "கிலோ பாஸ்பரஸ் (P)",
    forRootDev: "வேர் வளர்ச்சிக்கு",
    kgPotassium: "கிலோ பொட்டாசியம் (K)",
    forFruitDisease: "பழம் & நோய் எதிர்ப்பு",
    recommendedProducts: "பரிந்துரைக்கப்பட்ட உர தயாரிப்புகள்",
    applicationMethod: "பயன்பாட்டு முறை",
    bestTiming: "சிறந்த நேரம்",
    warnings: "எச்சரிக்கைகள்",
    mlAlgoDetails: "🧠 ML அல்காரிதம் விவரங்கள்",
    selectCropError: "பயிரைத் தேர்ந்தெடுக்கவும்",
    predictionComplete: "பின்புலத்திலிருந்து ML கணிப்பு முடிந்தது!",
    predictionFailed: "கணிப்பைப் பெற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    selectLocation: "இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்",
    currentLocation: "தற்போதைய இருப்பிடம்",
    fetchingWeather: "வானிலை தரவைப் பெறுகிறது...",
    unableToFetch: "வானிலை தரவைப் பெற இயலவில்லை",
    tryAgain: "பின்னர் மீண்டும் முயற்சிக்கவும்",
    humidity: "ஈரப்பதம்",
    wind: "காற்று",
    feelsLike: "உணர்வு",
    goodForHarvest: "✓ அறுவடைக்கு நல்லது",
    waitToHarvest: "⏳ அறுவடைக்கு காத்திருங்கள்",
  },
  hi: {
    appName: "Farm AI",
    subtitle: "आपका स्मार्ट खेती साथी",
    getStarted: "शुरू करें",
    howItWorks: "यह कैसे काम करता है",
    howItWorksSubtitle: "स्मार्ट खेती के लिए इन 4 सरल चरणों का पालन करें",
    checkWeather: "मौसम देखें",
    checkWeatherDesc: "अपने स्थान के लिए रीयल-टाइम मौसम और फसल कटाई की सिफारिशें प्राप्त करें।",
    analyzeCrop: "फसल का विश्लेषण करें",
    analyzeCropDesc: "रोग पहचान के लिए फोटो लें या वॉइस प्रश्न पूछें।",
    mlPrediction: "ML उर्वरक भविष्यवाणी",
    mlPredictionDesc: "सटीक NPK सिफारिशों के लिए फसल और मिट्टी का विवरण दर्ज करें।",
    fertilizerGuide: "उर्वरक गाइड",
    fertilizerGuideDesc: "अपनी विशिष्ट फसल और मिट्टी के प्रकार के लिए विस्तृत गाइड ब्राउज़ करें।",
    beginStep1: "चरण 1 शुरू करें",
    weatherTitle: "मौसम और फसल कटाई सिफारिश",
    weatherSubtitle: "आपके खेत के स्थान के लिए रीयल-टाइम मौसम विश्लेषण",
    nextCropAnalysis: "अगला: फसल विश्लेषण",
    cropAnalysisTitle: "फसल विश्लेषण और वॉइस सहायता",
    cropAnalysisSubtitle: "फसल की फोटो अपलोड करें या अपनी भाषा में प्रश्न पूछें",
    analyzeAndAsk: "फसल का विश्लेषण करें और प्रश्न पूछें",
    nextMLPredictor: "अगला: ML उर्वरक भविष्यवक्ता",
    mlPowered: "ML-संचालित भविष्यवाणी",
    nextFertilizerGuide: "अगला: उर्वरक गाइड",
    detailedFertilizerGuide: "विस्तृत उर्वरक गाइड",
    detailedFertilizerGuideSubtitle: "व्यापक फसल-विशिष्ट उर्वरक सिफारिशें",
    empowering: "स्मार्ट तकनीक से किसानों को सशक्त बनाना",
    copyright: "© 2024 Farm AI. किसानों के लिए ❤️ से बनाया गया",
    weather: "मौसम",
    cropAnalysis: "फसल विश्लेषण",
    mlPredictor: "ML भविष्यवक्ता",
    guide: "गाइड",
    cropImageAnalysis: "फसल छवि विश्लेषण",
    tapToCapture: "फसल की छवि लेने के लिए टैप करें",
    orUpload: "या गैलरी से अपलोड करें",
    camera: "कैमरा",
    upload: "अपलोड",
    analyzingCrop: "आपकी फसल का विश्लेषण कर रहे हैं...",
    analysisComplete: "विश्लेषण पूरा",
    captureNew: "नई छवि लें",
    cropHealthy: "🌾 फसल स्वस्थ दिखती है! अच्छी नमी का स्तर पाया गया। सुझाई गई कार्रवाई: नियमित सिंचाई कार्यक्रम जारी रखें। कटाई का अनुमानित समय: 2-3 सप्ताह।",
    voiceAssistant: "वॉइस सहायक",
    selectLanguage: "अपनी भाषा चुनें",
    processing: "प्रोसेसिंग...",
    listeningSpeak: "सुन रहा हूं... अब बोलें",
    tapToAsk: "प्रश्न पूछने के लिए टैप करें",
    askAbout: "कटाई, सिंचाई, कीट, उर्वरक या मौसम के बारे में पूछें",
    youSaid: "आपने कहा:",
    assistantResponse: "सहायक प्रतिक्रिया:",
    listen: "सुनें",
    speechNotSupported: "आपके ब्राउज़र में स्पीच रिकग्निशन समर्थित नहीं है। कृपया Chrome या Edge उपयोग करें।",
    failedMic: "माइक्रोफोन शुरू करने में विफल। कृपया अनुमतियाँ जांचें।",
    fertilizerPredictor: "उर्वरक भविष्यवक्ता",
    serverSideAlgo: "सर्वर-साइड डिसीजन ट्री + वेटेड स्कोरिंग एल्गोरिदम",
    inputParameters: "इनपुट पैरामीटर",
    cropType: "फसल प्रकार",
    selectCrop: "फसल चुनें",
    soilType: "मिट्टी का प्रकार",
    growthStage: "विकास चरण",
    weatherCondition: "मौसम की स्थिति",
    temperature: "तापमान (°C)",
    farmArea: "खेत का क्षेत्रफल (एकड़)",
    runningML: "ML एल्गोरिदम चल रहा है...",
    predictFertilizer: "उर्वरक आवश्यकताओं की भविष्यवाणी करें",
    predictionConfidence: "भविष्यवाणी विश्वास",
    basedOnDecision: "वेटेड स्कोरिंग के साथ डिसीजन ट्री वर्गीकरण पर आधारित",
    kgNitrogen: "किलो नाइट्रोजन (N)",
    forLeafGrowth: "पत्ती वृद्धि और क्लोरोफिल के लिए",
    kgPhosphorus: "किलो फॉस्फोरस (P)",
    forRootDev: "जड़ विकास के लिए",
    kgPotassium: "किलो पोटेशियम (K)",
    forFruitDisease: "फल और रोग प्रतिरोध के लिए",
    recommendedProducts: "अनुशंसित उर्वरक उत्पाद",
    applicationMethod: "उपयोग विधि",
    bestTiming: "सर्वोत्तम समय",
    warnings: "चेतावनियां",
    mlAlgoDetails: "🧠 ML एल्गोरिदम विवरण",
    selectCropError: "कृपया फसल चुनें",
    predictionComplete: "बैकएंड से ML भविष्यवाणी पूरी!",
    predictionFailed: "भविष्यवाणी प्राप्त करने में विफल। कृपया पुनः प्रयास करें।",
    selectLocation: "स्थान चुनें",
    currentLocation: "वर्तमान स्थान",
    fetchingWeather: "मौसम डेटा प्राप्त कर रहे हैं...",
    unableToFetch: "मौसम डेटा प्राप्त करने में असमर्थ",
    tryAgain: "कृपया बाद में पुनः प्रयास करें",
    humidity: "नमी",
    wind: "हवा",
    feelsLike: "महसूस होता है",
    goodForHarvest: "✓ कटाई के लिए अच्छा",
    waitToHarvest: "⏳ कटाई के लिए प्रतीक्षा करें",
  },
  te: {
    appName: "Farm AI",
    subtitle: "మీ స్మార్ట్ వ్యవసాయ సహచరుడు",
    getStarted: "ప్రారంభించండి",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    howItWorksSubtitle: "స్మార్ట్ వ్యవసాయానికి ఈ 4 సులభ దశలను అనుసరించండి",
    checkWeather: "వాతావరణం చూడండి",
    checkWeatherDesc: "మీ ప్రాంతానికి రియల్-టైమ్ వాతావరణం & పంట కోత సిఫార్సులు పొందండి.",
    analyzeCrop: "పంటను విశ్లేషించండి",
    analyzeCropDesc: "వ్యాధి గుర్తింపుకు ఫోటో తీయండి లేదా వాయిస్ ప్రశ్నలు అడగండి.",
    mlPrediction: "ML ఎరువుల అంచనా",
    mlPredictionDesc: "ఖచ్చితమైన NPK సిఫార్సులకు పంట & నేల వివరాలు నమోదు చేయండి.",
    fertilizerGuide: "ఎరువుల గైడ్",
    fertilizerGuideDesc: "మీ నిర్దిష్ట పంట మరియు నేల రకానికి వివరమైన గైడ్‌లను చూడండి.",
    beginStep1: "దశ 1 ప్రారంభించండి",
    weatherTitle: "వాతావరణం & పంట కోత సిఫార్సు",
    weatherSubtitle: "మీ పొలం ప్రాంతానికి రియల్-టైమ్ వాతావరణ విశ్లేషణ",
    nextCropAnalysis: "తదుపరి: పంట విశ్లేషణ",
    cropAnalysisTitle: "పంట విశ్లేషణ & వాయిస్ సహాయం",
    cropAnalysisSubtitle: "పంట ఫోటో అప్‌లోడ్ చేయండి లేదా మీ భాషలో ప్రశ్నలు అడగండి",
    analyzeAndAsk: "పంటను విశ్లేషించి ప్రశ్నలు అడగండి",
    nextMLPredictor: "తదుపరి: ML ఎరువుల అంచనాకారు",
    mlPowered: "ML-ఆధారిత అంచనా",
    nextFertilizerGuide: "తదుపరి: ఎరువుల గైడ్",
    detailedFertilizerGuide: "వివరమైన ఎరువుల గైడ్",
    detailedFertilizerGuideSubtitle: "సమగ్ర పంట-నిర్దిష్ట ఎరువుల సిఫార్సులు",
    empowering: "స్మార్ట్ టెక్నాలజీతో రైతులను బలోపేతం చేయడం",
    copyright: "© 2024 Farm AI. రైతుల కోసం ❤️ తో తయారు చేయబడింది",
    weather: "వాతావరణం",
    cropAnalysis: "పంట విశ్లేషణ",
    mlPredictor: "ML అంచనాకారు",
    guide: "గైడ్",
    cropImageAnalysis: "పంట చిత్ర విశ్లేషణ",
    tapToCapture: "పంట చిత్రాన్ని తీయడానికి నొక్కండి",
    orUpload: "లేదా గ్యాలరీ నుండి అప్‌లోడ్ చేయండి",
    camera: "కెమెరా",
    upload: "అప్‌లోడ్",
    analyzingCrop: "మీ పంటను విశ్లేషిస్తోంది...",
    analysisComplete: "విశ్లేషణ పూర్తయింది",
    captureNew: "కొత్త చిత్రం తీయండి",
    cropHealthy: "🌾 పంట ఆరోగ్యంగా కనిపిస్తోంది! మంచి తేమ స్థాయిలు కనుగొనబడ్డాయి. సిఫార్సు చర్య: సాధారణ నీటిపారుదల షెడ్యూల్‌ను కొనసాగించండి. పంట కోతకు అంచనా సమయం: 2-3 వారాలు.",
    voiceAssistant: "వాయిస్ సహాయకుడు",
    selectLanguage: "మీ భాషను ఎంచుకోండి",
    processing: "ప్రాసెసింగ్...",
    listeningSpeak: "వింటోంది... ఇప్పుడు మాట్లాడండి",
    tapToAsk: "ప్రశ్న అడగడానికి నొక్కండి",
    askAbout: "పంట కోత, నీటిపారుదల, పురుగులు, ఎరువులు లేదా వాతావరణం గురించి అడగండి",
    youSaid: "మీరు చెప్పింది:",
    assistantResponse: "సహాయకుడి ప్రతిస్పందన:",
    listen: "వినండి",
    speechNotSupported: "మీ బ్రౌజర్‌లో స్పీచ్ రికగ్నిషన్ మద్దతు లేదు. దయచేసి Chrome లేదా Edge ఉపయోగించండి.",
    failedMic: "మైక్రోఫోన్ ప్రారంభించడంలో విఫలమైంది. దయచేసి అనుమతులను తనిఖీ చేయండి.",
    fertilizerPredictor: "ఎరువుల అంచనాకారు",
    serverSideAlgo: "సర్వర్-సైడ్ డెసిషన్ ట్రీ + వెయిటెడ్ స్కోరింగ్ అల్గారిథం",
    inputParameters: "ఇన్‌పుట్ పారామీటర్లు",
    cropType: "పంట రకం",
    selectCrop: "పంట ఎంచుకోండి",
    soilType: "నేల రకం",
    growthStage: "ఎదుగుదల దశ",
    weatherCondition: "వాతావరణ పరిస్థితి",
    temperature: "ఉష్ణోగ్రత (°C)",
    farmArea: "పొలం విస్తీర్ణం (ఎకరాలు)",
    runningML: "ML అల్గారిథం నడుస్తోంది...",
    predictFertilizer: "ఎరువుల అవసరాలను అంచనా వేయండి",
    predictionConfidence: "అంచనా నమ్మకం",
    basedOnDecision: "వెయిటెడ్ స్కోరింగ్‌తో డెసిషన్ ట్రీ వర్గీకరణ ఆధారంగా",
    kgNitrogen: "కిలో నత్రజని (N)",
    forLeafGrowth: "ఆకు పెరుగుదల & క్లోరోఫిల్ కోసం",
    kgPhosphorus: "కిలో భాస్వరం (P)",
    forRootDev: "వేరు అభివృద్ధి కోసం",
    kgPotassium: "కిలో పొటాషియం (K)",
    forFruitDisease: "పండు & వ్యాధి నిరోధకత కోసం",
    recommendedProducts: "సిఫార్సు చేయబడిన ఎరువుల ఉత్పత్తులు",
    applicationMethod: "అప్లికేషన్ పద్ధతి",
    bestTiming: "ఉత్తమ సమయం",
    warnings: "హెచ్చరికలు",
    mlAlgoDetails: "🧠 ML అల్గారిథం వివరాలు",
    selectCropError: "దయచేసి పంట ఎంచుకోండి",
    predictionComplete: "బ్యాకెండ్ నుండి ML అంచనా పూర్తయింది!",
    predictionFailed: "అంచనా పొందడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    selectLocation: "ప్రాంతాన్ని ఎంచుకోండి",
    currentLocation: "ప్రస్తుత ప్రాంతం",
    fetchingWeather: "వాతావరణ డేటాను పొందుతోంది...",
    unableToFetch: "వాతావరణ డేటాను పొందలేకపోయింది",
    tryAgain: "దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి",
    humidity: "తేమ",
    wind: "గాలి",
    feelsLike: "అనిపిస్తుంది",
    goodForHarvest: "✓ పంట కోతకు మంచిది",
    waitToHarvest: "⏳ పంట కోతకు వేచి ఉండండి",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
